auth0:
  audience: https://www.yogaenpevele.fr/api
  client-name: auth0
  server-url: https://soldiertt.eu.auth0.com/api/v2/
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: admin
    url: jdbc:postgresql://localhost:5432/yoga
    username: admin
  jpa:
    generate-ddl: true
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          auth0:
            authorization-grant-type: client_credentials
            scope:
              - read:users
        provider:
          auth0:
            token-uri: https://soldiertt.eu.auth0.com/oauth/token
      resourceserver:
        jwt:
          issuer-uri: https://soldiertt.eu.auth0.com/